### ISSUE TITLE
linked properties both need column attribute

### ISSUE THREAD

**Issue by dtaylor-530** [podgito/DataTableMapper#10]
I has two linked numerical properties: one with a 'ColumnMappingAttribute' ; one without. The property without the column-attribute, when mapped, was set to 0, rather than the value of the property with the attribute. 
The solution was to give both the a 'ColumnMappingAttribute'.
Perhaps add a note to others?
Otherwise thanks for the package.

**Comment by podgito** [comment]
Hi,

Just to fully understand what tube said could you show me a sample of your
code and a sample dataset?

I'd be happy to help clarify for you and/or update my documentation to make
it clearer for everyone.

Thanks

**Comment by dtaylor-530** [comment]
Well it didn't have anything to do with the dataset - it was about how the code was written:
here it is, as it was, with the error

        [ColumnMapping("O_H")]
        public decimal AvgH { get; set; }
        [ColumnMapping("O_D")]
        public decimal AvgD { get; set; }
        [ColumnMapping("O_A")]
        public decimal AvgA { get; set; }

        public decimal HomeOdd { get { return AvgH; } set {AvgH = value;}} 

        public decimal DrawOdd { get { return AvgD; } set { AvgD = value; } }

        public decimal AwayOdd { get { return AvgA; } set { AvgA = value; } }`

And the without the error

        [ColumnMapping("O_H")]
        public decimal AvgH { get; set; }
        [ColumnMapping("O_D")]
        public decimal AvgD { get; set; }
        [ColumnMapping("O_A")]
        public decimal AvgA { get; set; }
        [ColumnMapping("O_H")]
        public decimal HomeOdd { get { return AvgH; } set {AvgH = value;}} 
        [ColumnMapping("O_D")]
        public decimal DrawOdd { get { return AvgD; } set { AvgD = value; } }
        [ColumnMapping("O_A")]
        public decimal AwayOdd { get { return AvgA; } set { AvgA = value; } }`

**Comment by podgito** [comment]
Ah I understand better now.

I think if you wanted to implement it like the first way, I think you need
to get rid of the setter for the HomeOdd, DrawOdd and AwayOdd properties.

I will investigate the behaviour anyway.

Thanks



On 10 Jan 2018 16:57, "dtaylor-530" <notifications@github.com> wrote:

Well it didn't have anything to do with the dataset - it was about how the
code was written:
here it is, as it was, with the error

    [ColumnMapping("O_H")]
    public decimal AvgH { get; set; }
    [ColumnMapping("O_D")]
    public decimal AvgD { get; set; }
    [ColumnMapping("O_A")]
    public decimal AvgA { get; set; }

    public decimal HomeOdd { get { return AvgH; } set {AvgH = value;}}

    public decimal DrawOdd { get { return AvgD; } set { AvgD = value; } }

    public decimal AwayOdd { get { return AvgA; } set { AvgA = value; } }`

And the without the error

    [ColumnMapping("O_H")]
    public decimal AvgH { get; set; }
    [ColumnMapping("O_D")]
    public decimal AvgD { get; set; }
    [ColumnMapping("O_A")]
    public decimal AvgA { get; set; }
    [ColumnMapping("O_H")]
    public decimal HomeOdd { get { return AvgH; } set {AvgH = value;}}
    [ColumnMapping("O_D")]
    public decimal DrawOdd { get { return AvgD; } set { AvgD = value; } }
    [ColumnMapping("O_A")]
    public decimal AwayOdd { get { return AvgA; } set { AvgA = value; } }`

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/podgito/DataTableMapper/issues/10#issuecomment-356665494>,
or mute the thread
