### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IainBapty** [podgito/DataTableMapper#9]
Please consider adding a License file. I was considering using this but can't unless I know what license this is available under. Many thanks this looks very useful.

**Comment by podgito** [comment]
I will add a licence file asap and will let you know when this is done.
Should be today or tomorrow

On 22 Aug 2016 14:57, "IainBapty" <notifications@github.com> wrote:
>
> Please consider adding a License file. I was considering using this but
can't unless I know what license this is available under. Many thanks this
looks very useful.

**Comment by podgito** [comment]
MIT Licence added.
